name: "Magento 2 Coding Standard"
on:
  pull_request:
  push:
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:2.3, phpcs:3.6
      - name: Run coding standard analysis
        uses: codemanufacture/magento-coding-standard-action@main
        with:
          severity: 5
